project:
  type: book
  
keywords:
- statistics
- modelling
- introduction
- course
- data analysis
- R



book:
  title: "stats-nutshell"
  author: 
    - name: Sebastian Sauer
      orcid: 0000-0003-1515-8348
  date: now
  doi: 10.5281/zenodo.10082518
  description: "A crash course on applied statistics with a focus on statistical modelling"
  repo-url: https://github.com/sebastiansauer/stats-nutshell
  repo-actions: [source, issue]
  chapters:
    - index.qmd
    # - 010-goals.qmd
    - 020-basics.qmd
    - 030-EDA.qmd
    - 040-inference.qmd
    - 050-regression1.qmd
    - 060-regression2.qmd
    - 070-causality.qmd
    - 080-outro.qmd
    - references.qmd
  sidebar: 
      logo: img/logo-stats-nutshell.png
      search: true
  favicon: img/logo-stats-nutshell.png
  

bibliography: "ses.bib"
csl: "apa7.csl"


  
lang: en
citation: true
#google-scholar: true
description: |
  A crash course on applied statistics with a focus on statistical modelling
license: "MIT" 


format:
  html:
    toc: true
    toc-depth: 3
    #toc-expand: 2
    theme:
      light: lumen
      dark: darkly
    number-sections: true
    df-print: kable
    fig-align: center
    mermaid:
      theme: default
  # pdf:
  #   toc: true
  #   number-sections: true
  #   colorlinks: true
  #   keep-tex: true

    
execute:
  warning: false   
  cache: true
  echo: true
    

editor: source 
keep-md: false 

knitr: 
  opts_chunk: 
    fig-align: center
    out-width: "70%"
    


